version: '3.4'

services:
  ocelotgateway:
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80


    ports:
      - "5230:80"

    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/UserSecrets
      - ${USERPROFILE}\.aspnet\https\OcelotGateway.pfx:/root/.aspnet/https/OcelotGateway.pfx
      